//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace openBasculaNet.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSITO_ACTUALES
    {
        public int ID_TRANSITO { get; set; }
        public string NUM_ALBARAN { get; set; }
        public string MAT_CABINA { get; set; }
        public string MAT_REMOLQUE { get; set; }
        public Nullable<System.DateTime> FECHA_ENTRADA { get; set; }
        public Nullable<System.DateTime> FECHA_SALIDA { get; set; }
        public Nullable<int> BRUTO { get; set; }
        public Nullable<int> TARA { get; set; }
        public Nullable<int> NETO { get; set; }
        public string IVA_APLICABLE { get; set; }
        public string IMPORTE_FINAL { get; set; }
        public string IMPORTE_PRODUCTO { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public Nullable<int> ID_PROVEEDOR { get; set; }
        public Nullable<int> ID_AGENCIA { get; set; }
        public Nullable<int> ID_POSEEDOR { get; set; }
        public Nullable<int> ID_CONDUCTOR { get; set; }
        public string ORIGEN { get; set; }
        public string DESTINO { get; set; }
    }
}
