CREATE TABLE [obn].[CONDUCTORES] (
    [ID_CONDUCTOR] INT          NOT NULL IDENTITY,
    [ID_EMPRESA]   INT          NULL,
    [FECHA_ALTA]   DATE         NULL,
    [FECHA_BAJA]   DATE         NULL,
    [NOMBRE]       VARCHAR (50) NULL,
    [APELLIDOS]    VARCHAR (50) NULL,
    [NIF]          VARCHAR (50) NULL,
    [DIRECCION]    VARCHAR (50) NULL,
    [LOCALIDAD]    VARCHAR (50) NULL,
    [PROVINCIA]    VARCHAR (50) NULL,
    [TELEFONO]     VARCHAR (50) NULL,
    [EMAIL]        VARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([ID_CONDUCTOR] ASC)
);

