CREATE TABLE [obn].[EMPRESAS] (
    [ID_EMPRESA]      INT           IDENTITY (1, 1) NOT NULL,
    [NOMBRE]          VARCHAR (MAX) NULL,
    [RAZON_SOCIAL]    VARCHAR (MAX) NULL,
    [CIF]             VARCHAR (50)  NULL,
    [DIRECCION]       VARCHAR (MAX) NULL,
    [LOCALIDAD]       VARCHAR (250) NULL,
    [PROVINCIA]       VARCHAR (250) NULL,
    [TELEFONO]        VARCHAR (50)  NULL,
    [EMAIL]           VARCHAR (MAX) NULL,
    [CUENTA_BANCARIA] VARCHAR (MAX) NULL,
    [FORMA_DE_PAGO]   VARCHAR (50)  NULL,
    [CODIGO_CONTABLE] VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([ID_EMPRESA] ASC)
);

