//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace openBasculaNet.Core.Structures
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDUCTORES
    {
        public int ID_CONDUCTOR { get; set; }
        public Nullable<int> ID_EMPRESA { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
        public Nullable<System.DateTime> FECHA_BAJA { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public string NIF { get; set; }
        public string DIRECCION { get; set; }
        public string LOCALIDAD { get; set; }
        public string PROVINCIA { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
    }
}
