//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace openBasculaNet.Core.Structures
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas
    {
        public int ID_EMPRESA { get; set; }
        public string NOMBRE { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string CIF { get; set; }
        public string DIRECCION { get; set; }
        public string LOCALIDAD { get; set; }
        public string PROVINCIA { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public string CUENTA_BANCARIA { get; set; }
        public string FORMA_DE_PAGO { get; set; }
        public string CODIGO_CONTABLE { get; set; }
    }
}
