//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace openBasculaNet.Core.Structures
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORICOS
    {
        public int ID_HISTORICO { get; set; }
        public string NUM_ALBARAN { get; set; }
        public string MAT_CABINA { get; set; }
        public string MAT_REMOLQUE { get; set; }
        public Nullable<System.DateTime> FECHA_ENTRADA { get; set; }
        public Nullable<System.DateTime> FECHA_SALIDA { get; set; }
        public Nullable<int> PESO_ENTRADA { get; set; }
        public Nullable<int> PESO_SALIDA { get; set; }
        public Nullable<int> NETO { get; set; }
        public string ORIGEN { get; set; }
        public string DESTINO { get; set; }
        public string FORMA_PAGO { get; set; }
        public string IVA_APLICABLE { get; set; }
        public string IMPORTE_FINAL { get; set; }
        public string IMPORTE_SIN_IVA { get; set; }
        public string IMPORTE_PRODUCTO { get; set; }
        public Nullable<int> NOMBRE_PRODUCTO { get; set; }
        public string TIPO_MATERIAL { get; set; }
        public Nullable<int> COD_CONTA_PROD { get; set; }
        public string RAZON_SOCIAL_CLIENTE { get; set; }
        public string CIF_CLIENTE { get; set; }
        public string DIRECCION_CLIENTE { get; set; }
        public string TLF_CLIENTE { get; set; }
        public string UBICACION_CLIENTE { get; set; }
        public string COD_CONTA_CLIENTE { get; set; }
        public string RAZON_SOCIAL_PROVEEDOR { get; set; }
        public string CIF_PROVEEDOR { get; set; }
        public string DIRECCION_PROVEEDOR { get; set; }
        public string TLF_PROVEEDOR { get; set; }
        public string UBICACION_PROVEEDOR { get; set; }
        public string COD_CONTA_PROVEEDOR { get; set; }
        public string RAZON_SOCIAL_AGENCIA { get; set; }
        public string CIF_AGENCIA { get; set; }
        public string DIRECCION_AGENCIA { get; set; }
        public string TLF_AGENCIA { get; set; }
        public string UBICACION_AGENCIA { get; set; }
        public string COD_CONTA_AGENCIA { get; set; }
        public string RAZON_SOCIAL_POSEEDOR { get; set; }
        public string CIF_POSEEDOR { get; set; }
        public string DIRECCION_POSEEDOR { get; set; }
        public string TLF_POSEEDOR { get; set; }
        public string UBICACION_POSEEDOR { get; set; }
        public string COD_CONTA_POSEEDOR { get; set; }
        public string NOMBRE_CONDUCTOR { get; set; }
        public string NIF_CONDUCTOR { get; set; }
        public string DIRECCION_CONDUCTOR { get; set; }
        public string TLF_CONDUCTOR { get; set; }
        public string UBICACION_CONDUCTOR { get; set; }
    }
}
