//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace openBasculaNet.Core.Structures
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS
    {
        public int ID_PRODUCTO { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<double> PRECIO { get; set; }
        public Nullable<int> IVA_APLICADO { get; set; }
        public string TIPO_MATERIAL { get; set; }
        public string CODIGO_CONTABLE { get; set; }
        public Nullable<bool> ES_TARIFA_PLANA { get; set; }
    }
}
